# EX_14 아이유팬이 좋아할 만한 다른 아티스트 찾기

## 목표: 한국어 데이터로 챗봇 만들기

### lubric

1. CSR matrix가 정상적으로 만들어졌다: 사용자와 아이템 개수를 바탕으로 정확한 사이즈로 만들었다.
2. MF 모델이 정상적으로 훈련되어 그럴듯한 추천이 이루어졌다: 사용자와 아이템 벡터 내적수치가 의미있게 형성되었다.
3. 비슷한 영화 찾기와 유저에게 추천하기의 과정이 정상적으로 진행되었다: MF모델이 예측한 유저 선호도 및 아이템간 유사도, 기여도가 의미있게 측정되었다.


### 학습 목표

- 추천 시스템의 개념과 목적을 이해한다.
- Implicit 라이브러리를 활용하여 Matrix Factorization(이하 MF) 기반의 추천 모델을 만들어 본다.
- 음악 감상 기록을 활용하여 비슷한 아티스트를 찾고 아티스트를 추천해 본다.
- 추천 시스템에서 자주 사용되는 데이터 구조인 CSR Matrix을 익힌다
- 유저의 행위 데이터 중 Explicit data와 Implicit data의 차이점을 익힌다.
- 새로운 데이터셋으로 직접 추천 모델을 만들어 본다.


### 🚩keyword

✔ Recsys

### 1) 데이터 준비와 전처리

In [20]:
import os
import pandas as pd

rating_file_path=os.getenv('HOME') + '/aiffel/EXPLORATIONS/EX_14/recommendata_iu/data/ml-1m/ratings.dat'
ratings_cols = ['user_id', 'movie_id', 'ratings', 'timestamp']
ratings = pd.read_csv(rating_file_path, sep='::', names=ratings_cols, engine='python', encoding = "ISO-8859-1")
orginal_data_size = len(ratings)
ratings.head()

   user_id  movie_id  ratings  timestamp
0        1      1193        5  978300760
1        1       661        3  978302109
2        1       914        3  978301968
3        1      3408        4  978300275
4        1      2355        5  978824291

In [21]:
# 3점 이상만 남깁니다.

ratings = ratings[ratings['ratings']>=3]
filtered_data_size = len(ratings)

print(f'orginal_data_size: {orginal_data_size}, filtered_data_size: {filtered_data_size}')
print(f'Ratio of Remaining Data is {filtered_data_size / orginal_data_size:.2%}')

orginal_data_size: 1000209, filtered_data_size: 836478
Ratio of Remaining Data is 83.63%

In [22]:
# ratings 컬럼의 이름을 counts로 바꿉니다.

ratings.rename(columns={'ratings':'counts'}, inplace=True)

In [23]:
ratings['counts']

0          5
1          3
2          3
3          4
4          5
          ..
1000203    3
1000205    5
1000206    5
1000207    4
1000208    4
Name: counts, Length: 836478, dtype: int64

In [24]:
# 영화 제목을 보기 위해 메타 데이터를 읽어옵니다.

movie_file_path=os.getenv('HOME') + '/aiffel/EXPLORATIONS/EX_14/recommendata_iu/data/ml-1m/movies.dat'
cols = ['movie_id', 'title', 'genre'] 
movies = pd.read_csv(movie_file_path, sep='::', names=cols, engine='python', encoding='ISO-8859-1')
movies.head()

   movie_id                               title                         genre
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy

### 2) 데이터 탐색

In [25]:
# ratings에 있는 유니크한 영화 개수

ratings['movie_id'].nunique()

3628

In [26]:
# ratings에 있는 유니크한 사용자 수

ratings['user_id'].nunique()

6039

In [27]:
# 가장 인기 있는 영화 50개(인기순) 30개는 너무 적어서 50개 해봄

movie_count = ratings.groupby('movie_id')['user_id'].count()
ranking_50 = movie_count.sort_values(ascending=False).head(50)
ranking_50

movie_id
2858    3211
260     2910
1196    2885
1210    2716
2028    2561
589     2509
593     2498
1198    2473
1270    2460
2571    2434
480     2413
2762    2385
608     2371
110     2314
1580    2297
527     2257
1197    2252
2396    2213
1617    2210
318     2194
858     2167
1265    2121
1097    2102
2997    2066
2716    2051
296     2030
356     2022
1240    2019
1       2000
457     1941
1214    1920
3578    1798
2916    1786
2628    1783
50      1744
1259    1728
541     1722
1200    1720
1193    1680
919     1650
1221    1624
912     1623
2987    1605
2355    1599
1387    1598
1213    1595
1036    1593
1610    1587
2791    1586
34      1574
Name: user_id, dtype: int64

In [28]:
# ranking_50영화 이름으로 변환

movies.set_index('movie_id').loc[ranking_50.index]

,title,genre
movie_id,,
2858,American Beauty (1999),Comedy|Drama
260,Star Wars: Episode IV - A New Hope (1977),Action|Adventure|Fantasy|Sci-Fi
1196,Star Wars: Episode V - The Empire Strikes Back...,Action|Adventure|Drama|Sci-Fi|War
1210,Star Wars: Episode VI - Return of the Jedi (1983),Action|Adventure|Romance|Sci-Fi|War
2028,Saving Private Ryan (1998),Action|Drama|War
589,Terminator 2: Judgment Day (1991),Action|Sci-Fi|Thriller
593,"Silence of the Lambs, The (1991)",Drama|Thriller
1198,Raiders of the Lost Ark (1981),Action|Adventure
1270,Back to the Future (1985),Comedy|Sci-Fi
2571,"Matrix, The (1999)",Action|Sci-Fi|Thriller
480,Jurassic Park (1993),Action|Adventure|Sci-Fi
2762,"Sixth Sense, The (1999)",Thriller
608,Fargo (1996),Crime|Drama|Thriller
110,Braveheart (1995),Action|Drama|War
1580,Men in Black (1997),Action|Adventure|Comedy|Sci-Fi
527,Schindler's List (1993),Drama|War
1197,"Princess Bride, The (1987)",Action|Adventure|Comedy|Romance
2396,Shakespeare in Love (1998),Comedy|Romance
1617,L.A. Confidential (1997),Crime|Film-Noir|Mystery|Thriller
318,"Shawshank Redemption, The (1994)",Drama
858,"Godfather, The (1972)",Action|Crime|Drama
1265,Groundhog Day (1993),Comedy|Romance
1097,E.T. the Extra-Terrestrial (1982),Children's|Drama|Fantasy|Sci-Fi
2997,Being John Malkovich (1999),Comedy
2716,Ghostbusters (1984),Comedy|Horror
296,Pulp Fiction (1994),Crime|Drama
356,Forrest Gump (1994),Comedy|Romance|War
1240,"Terminator, The (1984)",Action|Sci-Fi|Thriller
1,Toy Story (1995),Animation|Children's|Comedy
457,"Fugitive, The (1993)",Action|Thriller
1214,Alien (1979),Action|Horror|Sci-Fi|Thriller
3578,Gladiator (2000),Action|Drama
2916,Total Recall (1990),Action|Adventure|Sci-Fi|Thriller
2628,Star Wars: Episode I - The Phantom Menace (1999),Action|Adventure|Fantasy|Sci-Fi
50,"Usual Suspects, The (1995)",Crime|Thriller
1259,Stand by Me (1986),Adventure|Comedy|Drama
541,Blade Runner (1982),Film-Noir|Sci-Fi
1200,Aliens (1986),Action|Sci-Fi|Thriller|War
1193,One Flew Over the Cuckoo's Nest (1975),Drama
919,"Wizard of Oz, The (1939)",Adventure|Children's|Drama|Musical
1221,"Godfather: Part II, The (1974)",Action|Crime|Drama
912,Casablanca (1942),Drama|Romance|War
2987,Who Framed Roger Rabbit? (1988),Adventure|Animation|Film-Noir
2355,"Bug's Life, A (1998)",Animation|Children's|Comedy
1387,Jaws (1975),Action|Horror
1213,GoodFellas (1990),Crime|Drama
1036,Die Hard (1988),Action|Thriller
1610,"Hunt for Red October, The (1990)",Action|Thriller
2791,Airplane! (1980),Comedy
34,Babe (1995),Children's|Comedy|Drama

### 3) 내가 선호하는 영화를 5가지 골라서 ratings에 추가

In [32]:
# 본인이 좋아하시는 데이터로 바꿔서 추가
my_favorite = [1270, 1, 1214, 1200, 919] #Back to the Future (1985), Toy Story (1995), Alien (1979), Aliens (1986), Wizard of Oz, The (1939)

# 'seohyun'이라는 user_id가 각 5점 평점 준 걸로 가정
my_fav_moive_list = pd.DataFrame({'user_id': ['seohyun']*5, 'movie_id': my_favorite, 'counts':[5]*5})

if not ratings.isin({'user_id':['seohyun']})['user_id'].any():  # user_id에 'seohyun'이라는 데이터가 없다면
    ratings = ratings.append(my_fav_moive_list)                 # 위에 임의로 만든 my_fav_moive_list 데이터를 추가해 줍니다. 

ratings.tail(10)       # 잘 추가되었는지 확인

         user_id  movie_id  counts    timestamp
1000203     6040      1090       3  956715518.0
1000205     6040      1094       5  956704887.0
1000206     6040       562       5  956704746.0
1000207     6040      1096       4  956715648.0
1000208     6040      1097       4  956715569.0
0        seohyun      1270       5          NaN
1        seohyun         1       5          NaN
2        seohyun      1214       5          NaN
3        seohyun      1200       5          NaN
4        seohyun       919       5          NaN

In [33]:
# indexing
# (참고) pandas.DataFrame.unique()은 특정 컬럼에 포함된 유니크한 데이터만 모아 줍니다. indexing 작업을 위해 매우 유용

# 고유한 유저, 영화를 찾아내는 코드
user_unique = ratings['user_id'].unique()
movie_unique = ratings['movie_id'].unique()

# 유저, 영화 indexing 하는 코드 idx는 index의 약자입니다.
user_to_idx = {v:k for k,v in enumerate(user_unique)}
movie_to_idx = {v:k for k,v in enumerate(movie_unique)}

In [34]:
# 인덱싱이 잘 되었는지 확인해 봅니다. 

print(user_to_idx['seohyun'])    
print(movie_to_idx[1])

6039
40

In [38]:
# indexing을 통해 데이터 컬럼 내 값을 바꾸는 코드
# dictionary 자료형의 get 함수는 https://wikidocs.net/16 을 참고하세요.

# user_to_idx.get을 통해 user_id 컬럼의 모든 값을 인덱싱한 Series를 구해 봅시다. 
# 혹시 정상적으로 인덱싱되지 않은 row가 있다면 인덱스가 NaN이 될 테니 dropna()로 제거합니다. 

temp_user_data = ratings['user_id'].map(user_to_idx.get).dropna()
if len(temp_user_data) == len(ratings):   # 모든 row가 정상적으로 인덱싱되었다면
    print('user_id column indexing OK!!')
    ratings['user_id'] = temp_user_data   # ratings['user_id']을 인덱싱된 Series로 교체해 줍니다. 
else:
    print('user_id column indexing Fail!!')

# movie_to_idx을 통해 movie_id 컬럼도 동일한 방식으로 인덱싱해 줍니다. 
temp_movie_data = ratings['movie_id'].map(movie_to_idx.get).dropna()
if len(temp_movie_data) == len(ratings):
    print('movie column indexing OK!!')
    ratings['movie_id'] = temp_movie_data
else:
    print('movie column indexing Fail!!')

ratings

user_id column indexing Fail!!
movie column indexing OK!!

    user_id  movie_id  counts    timestamp
0         0         0       5  978300760.0
1         0         1       3  978302109.0
2         0         2       3  978301968.0
3         0         3       4  978300275.0
4         0         4       5  978824291.0
..      ...       ...     ...          ...
0      6039        22       5          NaN
1      6039        40       5          NaN
2      6039       193       5          NaN
3      6039       651       5          NaN
4      6039         9       5          NaN

[836483 rows x 4 columns]

### 4) CSR matrix

In [39]:
from scipy.sparse import csr_matrix

num_user = ratings['user_id'].nunique()
num_movie = ratings['movie_id'].nunique()

csr_data = csr_matrix((ratings.counts, (ratings.user_id, ratings.movie_id)), shape= (num_user, num_movie))
csr_data

<6040x3628 sparse matrix of type '<class 'numpy.int64'>'
	with 836483 stored elements in Compressed Sparse Row format>

CSR matrix = user_id 6040, movie_id 3628

### 5) als_model = AlternatingLeastSquares 모델을 직접 구성하여 훈련

In [40]:
from implicit.als import AlternatingLeastSquares
import os
import numpy as np

# implicit 라이브러리에서 권장하고 있는 부분입니다. 학습 내용과는 무관합니다.
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['KMP_DUPLICATE_LIB_OK']='True'
os.environ['MKL_NUM_THREADS']='1'

In [41]:
# Implicit AlternatingLeastSquares 모델의 선언

als_model = AlternatingLeastSquares(factors=100, regularization=0.01, use_gpu=False, iterations=15, dtype=np.float32)

In [42]:
# als 모델은 input으로 (item X user 꼴의 matrix를 받기 때문에 Transpose해줍니다.)

csr_data_transpose = csr_data.T
csr_data_transpose

<3628x6040 sparse matrix of type '<class 'numpy.int64'>'
	with 836483 stored elements in Compressed Sparse Column format>

In [43]:
# 모델 훈련

als_model.fit(csr_data_transpose)

  0%|          | 0/15 [00:00<?, ?it/s]

### 6) 내가 선호하는 5가지 영화 중 하나와 그 외의 영화 하나를 골라 훈련된 모델이 예측한 나의 선호도를 파악해 보세요.

In [55]:
seohyun, Back_to_the_Future  = user_to_idx['seohyun'], movie_to_idx[1270]
seohyun_vector, Back_to_the_Future_vector = als_model.user_factors[seohyun], als_model.item_factors[Back_to_the_Future]

print('슝=3')

슝=3

In [57]:
seohyun_vector

array([ 0.0418265 ,  0.24288994,  1.0289947 ,  0.20313959, -0.91757447,
       -1.0454127 ,  0.09073793,  0.70119864,  0.49270615,  0.37777522,
       -0.29683772,  1.1901138 , -0.08408807, -0.04291779,  0.8238784 ,
       -0.45593077,  0.56071013, -0.637213  , -0.014367  ,  0.61817247,
        0.19847289,  0.43190452,  0.03863052, -0.59657174, -0.64204186,
        0.32050094,  0.04049874,  0.39499992, -0.47039354, -0.32927328,
       -0.11846159,  0.8862093 ,  0.2872978 ,  0.5596991 ,  1.1047785 ,
       -1.288452  , -0.20997386,  0.55942416, -0.5893386 ,  0.06093607,
        0.4228521 ,  0.52579325,  0.6884666 , -0.5379835 , -0.34410545,
       -0.49575537, -1.0778086 , -0.5685066 , -0.639825  , -0.4956583 ,
       -1.1761613 , -0.38617164,  0.10294868, -0.2718219 , -0.15610145,
        0.23070477, -0.02466656,  0.21860082,  0.29625863, -0.39508843,
       -0.19291097,  0.01290098, -0.16487423, -0.5785399 , -0.4910761 ,
       -0.08724622, -0.21572691,  0.33839896,  0.30065486, -0.48162735,
        0.46063444, -0.06715651, -1.0681208 , -0.2527864 ,  0.16268404,
        0.42114997, -0.04264858,  0.51641005, -0.44051152, -0.03832383,
       -0.59886444,  1.1117458 ,  0.6727116 ,  0.5399735 ,  0.04190758,
       -0.41476908,  0.19515814,  0.2510506 ,  0.04563738,  0.9035809 ,
        0.24643402, -0.11853933,  0.32470983,  0.06665276,  0.58942956,
       -0.07189648, -0.06645158,  0.50306743, -0.1554852 ,  0.48167223],
      dtype=float32)

In [58]:
Back_to_the_Future_vector

array([-0.00268473,  0.02906618,  0.04358092, -0.01468158, -0.01735455,
        0.00158028, -0.0061657 ,  0.01733554,  0.01348738,  0.02388779,
        0.01956679,  0.05757124,  0.00927005,  0.02512102,  0.01582305,
       -0.02889454,  0.01751983,  0.00297819,  0.00706867,  0.04676003,
       -0.02188571, -0.00215303, -0.03071255,  0.00534807, -0.00767788,
        0.01176814,  0.00465506,  0.02374802,  0.00287527, -0.02300715,
       -0.00783194,  0.02786229, -0.01267597,  0.02244652,  0.00163055,
        0.0056363 ,  0.00445475,  0.00614081, -0.00894829,  0.00082014,
       -0.00544362, -0.00214063,  0.0094281 , -0.01488995,  0.02018033,
       -0.00307917,  0.00656092,  0.00363316,  0.00617738, -0.01553907,
       -0.03165267, -0.02334121, -0.00151902,  0.01004385, -0.02048162,
        0.03520608,  0.01458682,  0.00682479, -0.00899305,  0.01146563,
        0.00339737,  0.01431738, -0.00706513, -0.00669967, -0.00836762,
        0.01034195, -0.01812642,  0.02005913,  0.0168563 ,  0.00328433,
        0.00152034, -0.02967133, -0.01513771, -0.00486557,  0.00580192,
        0.00510509,  0.02731135,  0.02997033,  0.00684421, -0.00205305,
       -0.00505462,  0.04095454,  0.02861043,  0.02355921, -0.00061682,
       -0.00465291, -0.00881713,  0.02613651,  0.0328439 ,  0.00578862,
        0.01002144, -0.00907478,  0.00061387,  0.04319505,  0.0603044 ,
        0.0257713 ,  0.01426319,  0.00975869, -0.01958064,  0.00900788],
      dtype=float32)

In [59]:
# seohyun과 Back_to_the_Future를 내적하는 코드

np.dot(seohyun_vector, Back_to_the_Future_vector)

0.51695144

In [64]:
# 모델이 Matrix, The에 대한 선호도를 어떻게 예측할지 한 번 보겠습니다.

Matrix_The = movie_to_idx[2571]
Matrix_The_vector = als_model.item_factors[Matrix_The]
np.dot(seohyun_vector, Matrix_The_vector)

0.27591392

다시 훈련!

factors를 늘리거나 iterations를 늘리기

In [65]:
als_model = AlternatingLeastSquares(factors=200, regularization=0.01, use_gpu=False, iterations=15, dtype=np.float32)

In [66]:
als_model.fit(csr_data_transpose)

  0%|          | 0/15 [00:00<?, ?it/s]

In [67]:
seohyun, Back_to_the_Future  = user_to_idx['seohyun'], movie_to_idx[1270]
seohyun_vector, Back_to_the_Future_vector = als_model.user_factors[seohyun], als_model.item_factors[Back_to_the_Future]

In [68]:
np.dot(seohyun_vector, Back_to_the_Future_vector)

0.7411872

0.51695144 -> 0.7411872 success!

### 7) 내가 좋아하는 영화와 비슷한 영화를 추천받기

In [69]:
movie_to_title = movies.set_index('movie_id')['title'].to_dict()
movie_to_title

{1: 'Toy Story (1995)',
 2: 'Jumanji (1995)',
 3: 'Grumpier Old Men (1995)',
 4: 'Waiting to Exhale (1995)',
 5: 'Father of the Bride Part II (1995)',
 6: 'Heat (1995)',
 7: 'Sabrina (1995)',
 8: 'Tom and Huck (1995)',
 9: 'Sudden Death (1995)',
 10: 'GoldenEye (1995)',
 11: 'American President, The (1995)',
 12: 'Dracula: Dead and Loving It (1995)',
 13: 'Balto (1995)',
 14: 'Nixon (1995)',
 15: 'Cutthroat Island (1995)',
 16: 'Casino (1995)',
 17: 'Sense and Sensibility (1995)',
 18: 'Four Rooms (1995)',
 19: 'Ace Ventura: When Nature Calls (1995)',
 20: 'Money Train (1995)',
 21: 'Get Shorty (1995)',
 22: 'Copycat (1995)',
 23: 'Assassins (1995)',
 24: 'Powder (1995)',
 25: 'Leaving Las Vegas (1995)',
 26: 'Othello (1995)',
 27: 'Now and Then (1995)',
 28: 'Persuasion (1995)',
 29: 'City of Lost Children, The (1995)',
 30: 'Shanghai Triad (Yao a yao yao dao waipo qiao) (1995)',
 31: 'Dangerous Minds (1995)',
 32: 'Twelve Monkeys (1995)',
 33: 'Wings of Courage (1995)',
 34: 'Babe (1995)',
 35: 'Carrington (1995)',
 36: 'Dead Man Walking (1995)',
 37: 'Across the Sea of Time (1995)',
 38: 'It Takes Two (1995)',
 39: 'Clueless (1995)',
 40: 'Cry, the Beloved Country (1995)',
 41: 'Richard III (1995)',
 42: 'Dead Presidents (1995)',
 43: 'Restoration (1995)',
 44: 'Mortal Kombat (1995)',
 45: 'To Die For (1995)',
 46: 'How to Make an American Quilt (1995)',
 47: 'Seven (Se7en) (1995)',
 48: 'Pocahontas (1995)',
 49: 'When Night Is Falling (1995)',
 50: 'Usual Suspects, The (1995)',
 51: 'Guardian Angel (1994)',
 52: 'Mighty Aphrodite (1995)',
 53: 'Lamerica (1994)',
 54: 'Big Green, The (1995)',
 55: 'Georgia (1995)',
 56: 'Kids of the Round Table (1995)',
 57: 'Home for the Holidays (1995)',
 58: 'Postino, Il (The Postman) (1994)',
 59: 'Confessional, The (Le Confessionnal) (1995)',
 60: 'Indian in the Cupboard, The (1995)',
 61: 'Eye for an Eye (1996)',
 62: "Mr. Holland's Opus (1995)",
 63: "Don't Be a Menace to South Central While Drinking Your Juice in the Hood (1996)",
 64: 'Two if by Sea (1996)',
 65: 'Bio-Dome (1996)',
 66: 'Lawnmower Man 2: Beyond Cyberspace (1996)',
 67: 'Two Bits (1995)',
 68: 'French Twist (Gazon maudit) (1995)',
 69: 'Friday (1995)',
 70: 'From Dusk Till Dawn (1996)',
 71: 'Fair Game (1995)',
 72: 'Kicking and Screaming (1995)',
 73: 'Misérables, Les (1995)',
 74: 'Bed of Roses (1996)',
 75: 'Big Bully (1996)',
 76: 'Screamers (1995)',
 77: 'Nico Icon (1995)',
 78: 'Crossing Guard, The (1995)',
 79: 'Juror, The (1996)',
 80: 'White Balloon, The (Badkonake Sefid ) (1995)',
 81: "Things to Do in Denver when You're Dead (1995)",
 82: "Antonia's Line (Antonia) (1995)",
 83: 'Once Upon a Time... When We Were Colored (1995)',
 84: 'Last Summer in the Hamptons (1995)',
 85: 'Angels and Insects (1995)',
 86: 'White Squall (1996)',
 87: 'Dunston Checks In (1996)',
 88: 'Black Sheep (1996)',
 89: 'Nick of Time (1995)',
 90: 'Journey of August King, The (1995)',
 92: 'Mary Reilly (1996)',
 93: 'Vampire in Brooklyn (1995)',
 94: 'Beautiful Girls (1996)',
 95: 'Broken Arrow (1996)',
 96: 'In the Bleak Midwinter (1995)',
 97: 'Hate (Haine, La) (1995)',
 98: 'Shopping (1994)',
 99: 'Heidi Fleiss: Hollywood Madam (1995)',
 100: 'City Hall (1996)',
 101: 'Bottle Rocket (1996)',
 102: 'Mr. Wrong (1996)',
 103: 'Unforgettable (1996)',
 104: 'Happy Gilmore (1996)',
 105: 'Bridges of Madison County, The (1995)',
 106: 'Nobody Loves Me (Keiner liebt mich) (1994)',
 107: 'Muppet Treasure Island (1996)',
 108: 'Catwalk (1995)',
 109: 'Headless Body in Topless Bar (1995)',
 110: 'Braveheart (1995)',
 111: 'Taxi Driver (1976)',
 112: 'Rumble in the Bronx (1995)',
 113: 'Before and After (1996)',
 114: "Margaret's Museum (1995)",
 115: 'Happiness Is in the Field (1995)',
 116: 'Anne Frank Remembered (1995)',
 117: "Young Poisoner's Handbook, The (1995)",
 118: 'If Lucy Fell (1996)',
 119: 'Steal Big, Steal Little (1995)',
 120: 'Race the Sun (1996)',
 121: 'Boys of St. Vincent, The (1993)',
 122: 'Boomerang (1992)',
 123: 'Chungking Express (1994)',
 124: "Star Maker, The (Uomo delle stelle, L') (1995)",
 125: 'Flirting With Disaster (1996)',
 126: 'NeverEnding Story III, The (1994)',
 127: 'Silence of the Palace, The (Saimt el Qusur) (1994)',
 128: "Jupiter's Wife (1994)",
 129: 'Pie in the Sky (1995)',
 130: 'Angela (1995)',
 131: 'Frankie Starlight (1995)',
 132: 'Jade (1995)',
 133: 'Nueba Yol (1995)',
 134: 'Sonic Outlaws (1995)',
 135: 'Down Periscope (1996)',
 136: 'From the Journals of Jean Seberg (1995)',
 137: 'Man of the Year (1995)',
 138: 'Neon Bible, The (1995)',
 139: 'Target (1995)',
 140: 'Up Close and Personal (1996)',
 141: 'Birdcage, The (1996)',
 142: 'Shadows (Cienie) (1988)',
 143: 'Gospa (1995)',
 144: 'Brothers McMullen, The (1995)',
 145: 'Bad Boys (1995)',
 146: 'Amazing Panda Adventure, The (1995)',
 147: 'Basketball Diaries, The (1995)',
 148: 'Awfully Big Adventure, An (1995)',
 149: 'Amateur (1994)',
 150: 'Apollo 13 (1995)',
 151: 'Rob Roy (1995)',
 152: 'Addiction, The (1995)',
 153: 'Batman Forever (1995)',
 154: 'Belle de jour (1967)',
 155: 'Beyond Rangoon (1995)',
 156: 'Blue in the Face (1995)',
 157: 'Canadian Bacon (1994)',
 158: 'Casper (1995)',
 159: 'Clockers (1995)',
 160: 'Congo (1995)',
 161: 'Crimson Tide (1995)',
 162: 'Crumb (1994)',
 163: 'Desperado (1995)',
 164: 'Devil in a Blue Dress (1995)',
 165: 'Die Hard: With a Vengeance (1995)',
 166: 'Doom Generation, The (1995)',
 167: 'Feast of July (1995)',
 168: 'First Knight (1995)',
 169: 'Free Willy 2: The Adventure Home (1995)',
 170: 'Hackers (1995)',
 171: 'Jeffrey (1995)',
 172: 'Johnny Mnemonic (1995)',
 173: 'Judge Dredd (1995)',
 174: 'Jury Duty (1995)',
 175: 'Kids (1995)',
 176: 'Living in Oblivion (1995)',
 177: 'Lord of Illusions (1995)',
 178: 'Love & Human Remains (1993)',
 179: 'Mad Love (1995)',
 180: 'Mallrats (1995)',
 181: 'Mighty Morphin Power Rangers: The Movie (1995)',
 182: 'Moonlight and Valentino (1995)',
 183: 'Mute Witness (1994)',
 184: 'Nadja (1994)',
 185: 'Net, The (1995)',
 186: 'Nine Months (1995)',
 187: 'Party Girl (1995)',
 188: 'Prophecy, The (1995)',
 189: 'Reckless (1995)',
 190: 'Safe (1995)',
 191: 'Scarlet Letter, The (1995)',
 192: 'Show, The (1995)',
 193: 'Showgirls (1995)',
 194: 'Smoke (1995)',
 195: 'Something to Talk About (1995)',
 196: 'Species (1995)',
 197: 'Stars Fell on Henrietta, The (1995)',
 198: 'Strange Days (1995)',
 199: 'Umbrellas of Cherbourg, The (Parapluies de Cherbourg, Les) (1964)',
 200: 'Tie That Binds, The (1995)',
 201: 'Three Wishes (1995)',
 202: 'Total Eclipse (1995)',
 203: 'To Wong Foo, Thanks for Everything! Julie Newmar (1995)',
 204: 'Under Siege 2: Dark Territory (1995)',
 205: 'Unstrung Heroes (1995)',
 206: 'Unzipped (1995)',
 207: 'Walk in the Clouds, A (1995)',
 208: 'Waterworld (1995)',
 209: "White Man's Burden (1995)",
 210: 'Wild Bill (1995)',
 211: 'Browning Version, The (1994)',
 212: 'Bushwhacked (1995)',
 213: 'Burnt By the Sun (Utomlyonnye solntsem) (1994)',
 214: 'Before the Rain (Pred dozhdot) (1994)',
 215: 'Before Sunrise (1995)',
 216: 'Billy Madison (1995)',
 217: 'Babysitter, The (1995)',
 218: 'Boys on the Side (1995)',
 219: 'Cure, The (1995)',
 220: 'Castle Freak (1995)',
 222: 'Circle of Friends (1995)',
 223: 'Clerks (1994)',
 224: 'Don Juan DeMarco (1995)',
 225: 'Disclosure (1994)',
 226: 'Dream Man (1995)',
 227: 'Drop Zone (1994)',
 228: 'Destiny Turns on the Radio (1995)',
 229: 'Death and the Maiden (1994)',
 230: 'Dolores Claiborne (1994)',
 231: 'Dumb & Dumber (1994)',
 232: 'Eat Drink Man Woman (1994)',
 233: 'Exotica (1994)',
 234: 'Exit to Eden (1994)',
 235: 'Ed Wood (1994)',
 236: 'French Kiss (1995)',
 237: 'Forget Paris (1995)',
 238: 'Far From Home: The Adventures of Yellow Dog (1995)',
 239: 'Goofy Movie, A (1995)',
 240: 'Hideaway (1995)',
 241: 'Fluke (1995)',
 242: 'Farinelli: il castrato (1994)',
 243: 'Gordy (1995)',
 244: 'Gumby: The Movie (1995)',
 245: 'Glass Shield, The (1994)',
 246: 'Hoop Dreams (1994)',
 247: 'Heavenly Creatures (1994)',
 248: 'Houseguest (1994)',
 249: 'Immortal Beloved (1994)',
 250: 'Heavyweights (1994)',
 251: 'Hunted, The (1995)',
 252: 'I.Q. (1994)',
 253: 'Interview with the Vampire (1994)',
 254: 'Jefferson in Paris (1995)',
 255: 'Jerky Boys, The (1994)',
 256: 'Junior (1994)',
 257: 'Just Cause (1995)',
 258: "Kid in King Arthur's Court, A (1995)",
 259: 'Kiss of Death (1995)',
 260: 'Star Wars: Episode IV - A New Hope (1977)',
 261: 'Little Women (1994)',
 262: 'Little Princess, A (1995)',
 263: 'Ladybird Ladybird (1994)',
 264: "Enfer, L' (1994)",
 265: 'Like Water for Chocolate (Como agua para chocolate) (1992)',
 266: 'Legends of the Fall (1994)',
 267: 'Major Payne (1994)',
 268: 'Little Odessa (1994)',
 269: 'My Crazy Life (Mi vida loca) (1993)',
 270: 'Love Affair (1994)',
 271: 'Losing Isaiah (1995)',
 272: 'Madness of King George, The (1994)',
 273: "Mary Shelley's Frankenstein (1994)",
 274: 'Man of the House (1995)',
 275: 'Mixed Nuts (1994)',
 276: 'Milk Money (1994)',
 277: 'Miracle on 34th Street (1994)',
 278: 'Miami Rhapsody (1995)',
 279: 'My Family (1995)',
 280: 'Murder in the First (1995)',
 281: "Nobody's Fool (1994)",
 282: 'Nell (1994)',
 283: 'New Jersey Drive (1995)',
 284: 'New York Cop (1996)',
 285: 'Beyond Bedlam (1993)',
 286: 'Nemesis 2: Nebula (1995)',
 287: 'Nina Takes a Lover (1994)',
 288: 'Natural Born Killers (1994)',
 289: 'Only You (1994)',
 290: 'Once Were Warriors (1994)',
 291: 'Poison Ivy II (1995)',
 292: 'Outbreak (1995)',
 293: 'Professional, The (a.k.a. Leon: The Professional) (1994)',
 294: 'Perez Family, The (1995)',
 295: "Pyromaniac's Love Story, A (1995)",
 296: 'Pulp Fiction (1994)',
 297: 'Panther (1995)',
 298: 'Pushing Hands (1992)',
 299: 'Priest (1994)',
 300: 'Quiz Show (1994)',
 301: 'Picture Bride (1995)',
 302: 'Queen Margot (La Reine Margot) (1994)',
 303: 'Quick and the Dead, The (1995)',
 304: 'Roommates (1995)',
 305: 'Ready to Wear (Pret-A-Porter) (1994)',
 306: 'Three Colors: Red (1994)',
 307: 'Three Colors: Blue (1993)',
 308: 'Three Colors: White (1994)',
 309: 'Red Firecracker, Green Firecracker (1994)',
 310: 'Rent-a-Kid (1995)',
 311: 'Relative Fear (1994)',
 312: 'Stuart Saves His Family (1995)',
 313: 'Swan Princess, The (1994)',
 314: 'Secret of Roan Inish, The (1994)',
 315: 'Specialist, The (1994)',
 316: 'Stargate (1994)',
 317: 'Santa Clause, The (1994)',
 318: 'Shawshank Redemption, The (1994)',
 319: 'Shallow Grave (1994)',
 320: 'Suture (1993)',
 321: 'Strawberry and Chocolate (Fresa y chocolate) (1993)',
 322: 'Swimming with Sharks (1995)',
 324: 'Sum of Us, The (1994)',
 325: "National Lampoon's Senior Trip (1995)",
 326: 'To Live (Huozhe) (1994)',
 327: 'Tank Girl (1995)',
 328: 'Tales From the Crypt Presents: Demon Knight (1995)',
 329: 'Star Trek: Generations (1994)',
 330: 'Tales from the Hood (1995)',
 331: 'Tom & Viv (1994)',
 332: 'Village of the Damned (1995)',
 333: 'Tommy Boy (1995)',
 334: 'Vanya on 42nd Street (1994)',
 335: 'Underneath, The (1995)',
 336: 'Walking Dead, The (1995)',
 337: "What's Eating Gilbert Grape (1993)",
 338: 'Virtuosity (1995)',
 339: 'While You Were Sleeping (1995)',
 340: 'War, The (1994)',
 341: 'Double Happiness (1994)',
 342: "Muriel's Wedding (1994)",
 343: 'Baby-Sitters Club, The (1995)',
 344: 'Ace Ventura: Pet Detective (1994)',
 345: 'Adventures of Priscilla, Queen of the Desert, The (1994)',
 346: 'Backbeat (1993)',
 347: 'Bitter Moon (1992)',
 348: 'Bullets Over Broadway (1994)',
 349: 'Clear and Present Danger (1994)',
 350: 'Client, The (1994)',
 351: 'Corrina, Corrina (1994)',
 352: 'Crooklyn (1994)',
 353: 'Crow, The (1994)',
 354: 'Cobb (1994)',
 355: 'Flintstones, The (1994)',
 356: 'Forrest Gump (1994)',
 357: 'Four Weddings and a Funeral (1994)',
 358: 'Higher Learning (1995)',
 359: 'I Like It Like That (1994)',
 360: 'I Love Trouble (1994)',
 361: 'It Could Happen to You (1994)',
 362: 'Jungle Book, The (1994)',
 363: 'Wonderful, Horrible Life of Leni Riefenstahl, The (Die Macht der Bilder) (1993)',
 364: 'Lion King, The (1994)',
 365: 'Little Buddha (1993)',
 366: "Wes Craven's New Nightmare (1994)",
 367: 'Mask, The (1994)',
 368: 'Maverick (1994)',
 369: 'Mrs. Parker and the Vicious Circle (1994)',
 370: 'Naked Gun 33 1/3: The Final Insult (1994)',
 371: 'Paper, The (1994)',
 372: 'Reality Bites (1994)',
 373: 'Red Rock West (1992)',
 374: 'Richie Rich (1994)',
 375: 'Safe Passage (1994)',
 376: 'River Wild, The (1994)',
 377: 'Speed (1994)',
 378: 'Speechless (1994)',
 379: 'Timecop (1994)',
 380: 'True Lies (1994)',
 381: 'When a Man Loves a Woman (1994)',
 382: 'Wolf (1994)',
 383: 'Wyatt Earp (1994)',
 384: 'Bad Company (1995)',
 385: 'Man of No Importance, A (1994)',
 386: 'S.F.W. (1994)',
 387: 'Low Down Dirty Shame, A (1994)',
 388: 'Boys Life (1995)',
 389: 'Colonel Chabert, Le (1994)',
 390: 'Faster Pussycat! Kill! Kill! (1965)',
 391: "Jason's Lyric (1994)",
 392: 'Secret Adventures of Tom Thumb, The (1993)',
 393: 'Street Fighter (1994)',
 394: 'Coldblooded (1995)',
 395: 'Desert Winds (1995)',
 396: 'Fall Time (1995)',
 397: 'Fear, The (1995)',
 398: 'Frank and Ollie (1995)',
 399: 'Girl in the Cadillac (1995)',
 400: 'Homage (1995)',
 401: 'Mirage (1995)',
 402: 'Open Season (1996)',
 403: 'Two Crimes (1995)',
 404: 'Brother Minister: The Assassination of Malcolm X (1994)',
 405: 'Highlander III: The Sorcerer (1994)',
 406: 'Federal Hill (1994)',
 407: 'In the Mouth of Madness (1995)',
 408: '8 Seconds (1994)',
 409: 'Above the Rim (1994)',
 410: 'Addams Family Values (1993)',
 411: 'You So Crazy (1994)',
 412: 'Age of Innocence, The (1993)',
 413: 'Airheads (1994)',
 414: 'Air Up There, The (1994)',
 415: 'Another Stakeout (1993)',
 416: 'Bad Girls (1994)',
 417: 'Barcelona (1994)',
 418: 'Being Human (1993)',
 419: 'Beverly Hillbillies, The (1993)',
 420: 'Beverly Hills Cop III (1994)',
 421: 'Black Beauty (1994)',
 422: 'Blink (1994)',
 423: 'Blown Away (1994)',
 424: 'Blue Chips (1994)',
 425: 'Blue Sky (1994)',
 426: 'Body Snatchers (1993)',
 427: 'Boxing Helena (1993)',
 428: 'Bronx Tale, A (1993)',
 429: 'Cabin Boy (1994)',
 430: 'Calendar Girl (1993)',
 431: "Carlito's Way (1993)",
 432: "City Slickers II: The Legend of Curly's Gold (1994)",
 433: 'Clean Slate (1994)',
 434: 'Cliffhanger (1993)',
 435: 'Coneheads (1993)',
 436: 'Color of Night (1994)',
 437: 'Cops and Robbersons (1994)',
 438: 'Cowboy Way, The (1994)',
 439: 'Dangerous Game (1993)',
 440: 'Dave (1993)',
 441: 'Dazed and Confused (1993)',
 442: 'Demolition Man (1993)',
 443: 'Endless Summer 2, The (1994)',
 444: 'Even Cowgirls Get the Blues (1993)',
 445: 'Fatal Instinct (1993)',
 446: 'Farewell My Concubine (1993)',
 447: 'Favor, The (1994)',
 448: 'Fearless (1993)',
 449: 'Fear of a Black Hat (1993)',
 450: 'With Honors (1994)',
 451: 'Flesh and Bone (1993)',
 452: "Widows' Peak (1994)",
 453: 'For Love or Money (1993)',
 454: 'Firm, The (1993)',
 455: 'Free Willy (1993)',
 456: 'Fresh (1994)',
 457: 'Fugitive, The (1993)',
 458: 'Geronimo: An American Legend (1993)',
 459: 'Getaway, The (1994)',
 460: 'Getting Even with Dad (1994)',
 461: 'Go Fish (1994)',
 462: 'Good Man in Africa, A (1994)',
 463: 'Guilty as Sin (1993)',
 464: 'Hard Target (1993)',
 465: 'Heaven & Earth (1993)',
 466: 'Hot Shots! Part Deux (1993)',
 467: 'Live Nude Girls (1995)',
 468: 'Englishman Who Went Up a Hill, But Came Down a Mountain, The (1995)',
 469: 'House of the Spirits, The (1993)',
 470: 'House Party 3 (1994)',
 471: 'Hudsucker Proxy, The (1994)',
 472: "I'll Do Anything (1994)",
 473: 'In the Army Now (1994)',
 474: 'In the Line of Fire (1993)',
 475: 'In the Name of the Father (1993)',
 476: 'Inkwell, The (1994)',
 477: "What's Love Got to Do with It? (1993)",
 478: 'Jimmy Hollywood (1994)',
 479: 'Judgment Night (1993)',
 480: 'Jurassic Park (1993)',
 481: 'Kalifornia (1993)',
 482: 'Killing Zoe (1994)',
 483: 'King of the Hill (1993)',
 484: 'Lassie (1994)',
 485: 'Last Action Hero (1993)',
 486: 'Life with Mikey (1993)',
 487: 'Lightning Jack (1994)',
 488: 'M. Butterfly (1993)',
 489: 'Made in America (1993)',
 490: 'Malice (1993)',
 491: 'Man Without a Face, The (1993)',
 492: 'Manhattan Murder Mystery (1993)',
 493: 'Menace II Society (1993)',
 494: 'Executive Decision (1996)',
 495: 'In the Realm of the Senses (Ai no corrida) (1976)',
 496: 'What Happened Was... (1994)',
 497: 'Much Ado About Nothing (1993)',
 498: 'Mr. Jones (1993)',
 499: 'Mr. Wonderful (1993)',
 500: 'Mrs. Doubtfire (1993)',
 501: 'Naked (1993)',
 502: 'Next Karate Kid, The (1994)',
 503: 'New Age, The (1994)',
 504: 'No Escape (1994)',
 505: 'North (1994)',
 506: 'Orlando (1993)',
 507: 'Perfect World, A (1993)',
 508: 'Philadelphia (1993)',
 509: 'Piano, The (1993)',
 510: 'Poetic Justice (1993)',
 511: 'Program, The (1993)',
 512: "Robert A. Heinlein's The Puppet Masters (1994)",
 513: 'Radioland Murders (1994)',
 514: 'Ref, The (1994)',
 515: 'Remains of the Day, The (1993)',
 516: 'Renaissance Man (1994)',
 517: 'Rising Sun (1993)',
 518: 'Road to Wellville, The (1994)',
 519: 'Robocop 3 (1993)',
 520: 'Robin Hood: Men in Tights (1993)',
 521: 'Romeo Is Bleeding (1993)',
 522: 'Romper Stomper (1992)',
 523: 'Ruby in Paradise (1993)',
 524: 'Rudy (1993)',
 525: 'Saint of Fort Washington, The (1993)',
 526: 'Savage Nights (Nuits fauves, Les) (1992)',
 527: "Schindler's List (1993)",
 528: 'Scout, The (1994)',
 529: 'Searching for Bobby Fischer (1993)',
 530: 'Second Best (1994)',
 531: 'Secret Garden, The (1993)',
 532: 'Serial Mom (1994)',
 533: 'Shadow, The (1994)',
 534: 'Shadowlands (1993)',
 535: 'Short Cuts (1993)',
 536: 'Simple Twist of Fate, A (1994)',
 537: 'Sirens (1994)',
 538: 'Six Degrees of Separation (1993)',
 539: 'Sleepless in Seattle (1993)',
 540: 'Sliver (1993)',
 541: 'Blade Runner (1982)',
 542: 'Son in Law (1993)',
 543: 'So I Married an Axe Murderer (1993)',
 544: 'Striking Distance (1993)',
 545: 'Harlem (1993)',
 546: 'Super Mario Bros. (1993)',
 547: 'Surviving the Game (1994)',
 548: 'Terminal Velocity (1994)',
 549: 'Thirty-Two Short Films About Glenn Gould (1993)',
 550: 'Threesome (1994)',
 551: 'Nightmare Before Christmas, The (1993)',
 552: 'Three Musketeers, The (1993)',
 553: 'Tombstone (1993)',
 554: 'Trial by Jury (1994)',
 555: 'True Romance (1993)',
 556: 'War Room, The (1993)',
 557: 'Mamma Roma (1962)',
 558: 'Pagemaster, The (1994)',
 559: 'Paris, France (1993)',
 560: 'Beans of Egypt, Maine, The (1994)',
 561: 'Killer (Bulletproof Heart) (1994)',
 562: 'Welcome to the Dollhouse (1995)',
 563: 'Germinal (1993)',
 564: 'Chasers (1994)',
 565: 'Cronos (1992)',
 566: 'Naked in New York (1994)',
 567: 'Kika (1993)',
 568: 'Bhaji on the Beach (1993)',
 569: 'Little Big League (1994)',
 570: 'Slingshot, The (Kådisbellan ) (1993)',
 571: 'Wedding Gift, The (1994)',
 572: 'Foreign Student (1994)',
 573: 'Ciao, Professore! (Io speriamo che me la cavo ) (1993)',
 574: 'Spanking the Monkey (1994)',
 575: 'Little Rascals, The (1994)',
 576: 'Fausto (1993)',
 577: 'Andre (1994)',
 578: 'Hour of the Pig, The (1993)',
 579: 'Scorta, La (1993)',
 580: 'Princess Caraboo (1994)',
 581: 'Celluloid Closet, The (1995)',
 582: 'Metisse (Café au Lait) (1993)',
 583: 'Dear Diary (Caro Diario) (1994)',
 584: "I Don't Want to Talk About It (De eso no se habla) (1993)",
 585: 'Brady Bunch Movie, The (1995)',
 586: 'Home Alone (1990)',
 587: 'Ghost (1990)',
 588: 'Aladdin (1992)',
 589: 'Terminator 2: Judgment Day (1991)',
 590: 'Dances with Wolves (1990)',
 591: 'Tough and Deadly (1995)',
 592: 'Batman (1989)',
 593: 'Silence of the Lambs, The (1991)',
 594: 'Snow White and the Seven Dwarfs (1937)',
 595: 'Beauty and the Beast (1991)',
 596: 'Pinocchio (1940)',
 597: 'Pretty Woman (1990)',
 598: 'Window to Paris (1994)',
 599: 'Wild Bunch, The (1969)',
 600: 'Love and a .45 (1994)',
 601: "Wooden Man's Bride, The (Wu Kui) (1994)",
 602: 'Great Day in Harlem, A (1994)',
 603: 'Bye Bye, Love (1995)',
 604: 'Criminals (1996)',

In [70]:
# AlternatingLeastSquares 클래스에 구현되어 있는 similar_items 메서드를 통하여 비슷한 아티스트를 찾습니다. 
# 처음으로는 제가 좋아하는 toystory로 찾아보겠습니다.

favorite_movie = 1 #toy story
movie_id = movie_to_idx[favorite_movie]
similar_movie = als_model.similar_items(movie_id, N=15)
similar_movie

[(40, 1.0),
 (50, 0.5600084),
 (33, 0.38424897),
 (4, 0.35531524),
 (2938, 0.3382448),
 (330, 0.32582858),
 (2969, 0.3165465),
 (2598, 0.31447792),
 (1638, 0.31180647),
 (110, 0.31029776),
 (2608, 0.31001934),
 (2450, 0.3088003),
 (1825, 0.30745912),
 (3107, 0.30744147),
 (2531, 0.307409)]

In [71]:
# (영화의 id, 유사도) Tuple 로 반환하고 있습니다. 영화의 id를 다시 영화의 이름으로 매핑 시켜 주겠습니다.
#movie_to_idx 를 뒤집어, index로부터 movie_id를 얻는 dict를 생성 

idx_to_movie = {v:k for k,v in movie_to_idx.items()}
[movie_to_title[idx_to_movie[i[0]]] for i in similar_movie]

['Toy Story (1995)',
 'Toy Story 2 (1999)',
 'Aladdin (1992)',
 "Bug's Life, A (1998)",
 'Nobody Loves Me (Keiner liebt mich) (1994)',
 'Lion King, The (1994)',
 'Best Men (1997)',
 'Babyfever (1994)',
 'Walking Dead, The (1995)',
 'Groundhog Day (1993)',
 'Wisdom of Crocodiles, The (a.k.a. Immortality) (2000)',
 'Mad Love (1995)',
 'Secret Adventures of Tom Thumb, The (1993)',
 'New Rose Hotel (1998)',
 'Splendor (1999)']

### 8) 내가 가장 좋아할 만한 영화들을 추천받기

In [79]:
# AlternatingLeastSquares 클래스에 구현되어 있는 recommend 메서드를 통하여 제가 좋아할 만한 영화를 추천받습니다. 
# filter_already_liked_items 는 유저가 이미 평가한 아이템은 제외하는 Argument입니다.

user = user_to_idx['seohyun']
# recommend에서는 user*item CSR Matrix를 받습니다.
movie_recommended = als_model.recommend(user, csr_data, N=20, filter_already_liked_items=True)
movie_recommended

[(200, 0.5555308),
 (680, 0.33337063),
 (197, 0.30412468),
 (44, 0.28582567),
 (92, 0.27612925),
 (117, 0.27273878),
 (50, 0.26657787),
 (26, 0.23205966),
 (110, 0.22958627),
 (91, 0.22857578),
 (45, 0.2096439),
 (80, 0.1878095),
 (548, 0.18686527),
 (126, 0.18131755),
 (124, 0.17797619),
 (451, 0.17129102),
 (474, 0.17039931),
 (582, 0.17026412),
 (904, 0.166801),
 (154, 0.16461685)]

In [80]:
[movie_to_title[idx_to_movie[i[0]]] for i in movie_recommended]

['Terminator, The (1984)',
 'Blade Runner (1982)',
 'Jaws (1975)',
 'Star Wars: Episode IV - A New Hope (1977)',
 'Terminator 2: Judgment Day (1991)',
 'Star Wars: Episode V - The Empire Strikes Back (1980)',
 'Toy Story 2 (1999)',
 'E.T. the Extra-Terrestrial (1982)',
 'Groundhog Day (1993)',
 'Close Encounters of the Third Kind (1977)',
 'Mary Poppins (1964)',
 'Stand by Me (1986)',
 'Fantasia (1940)',
 'Shakespeare in Love (1998)',
 'Matrix, The (1999)',
 'American History X (1998)',
 'Chicken Run (2000)',
 'Beetlejuice (1988)',
 'Clockwork Orange, A (1971)',
 'As Good As It Gets (1997)']

In [85]:
# As Good As It Gets (1997) 추천에 기영한 영화의 기여 정도 확인

[movie_to_title[idx_to_movie[i[0]]] for i in movie_recommended].index('As Good As It Gets (1997)')

19

In [88]:
# lternatingLeastSquares 클래스에 구현된 explain 메서드를 사용하면 제가 기록을 남긴 데이터 중 이 추천에 기여한 정도를 확인할 수 있습니다.

As_Good_As_It_Gets = 154
explain = als_model.explain(user, csr_data, itemid=As_Good_As_It_Gets)

In [89]:
# 이 method는 추천한 콘텐츠의 점수에 기여한 다른 콘텐츠와 기여도(합이 콘텐츠의 점수가 됩니다.)를 반환합니다. 
# 어떤 영화들이 이 추천에 얼마나 기여하고 있는 걸까요?

[(movie_to_title[idx_to_movie[i[0]]], i[1]) for i in explain[1]]

[('Aliens (1986)', 0.04468779163776469),
 ('Toy Story (1995)', 0.0445735069494987),
 ('Wizard of Oz, The (1939)', 0.039592912473356195),
 ('Back to the Future (1985)', 0.03866775707940854),
 ('Alien (1979)', -0.00289020023344912)]

'Aliens (1986)', 0.04468779163776469), 'Toy Story (1995)', 0.0445735069494987)가 가장 높게 나타나지만 그래도 높은 수치는 아닌 것 같다.

### Trial and error

전체적으로 추천 시스템이 어떻게 돌아가는지 알 수 있는 노드이다. 해보면서 알 수 있었던 건 1) 추천 시스템은 관련 데이터에 대한 이해가 다른 파트보다 제일 중요하다 2) 추천 시스템을 만드는 건 누구나 할 수 있지만 개개인의 취향을 완전히 만족시킬 수 있도록 확률을 높이는 건 가장 어려울 수 있는 분야다 정도. 기회가 된다면 정말 깊게 해보고 싶었던 분야여서 나중에 꼭 그런 기회가 온다면 잡고 싶다. 이번 노드는 어려운 게 하나도 없어서 금방 할 수 있었던 과제였다 :)